development:
   adapter: mysql2
   database: chef_development
   username: supriti
   password: password
   host: localhost
   
test:
   adapter: mysql2
   database: chef_test
   username: supriti
   password: password
   host: localhost
   
production:
   adapter: mysql2
   database: chef_production
   username: supriti
   password: password
   host: localhost