# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eabf45691c4410ec0b7c0ad21f41cb7ec289936e97ba8ddb8fc8f8ae30b93e9526a48082406fcbeb63219257c4e2b1731affe3ccea75482e5e481c2e402fcfa9

test:
  secret_key_base: 2d925500389054d8b4bb194e48380bfa7bfa8c0ca8025cc7da4004bf113b3f451d8e4a48ba55210536f91bfe549820e3cb6b5e0b24a22a349ddc4f80d947bcc6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
